### ISSUE TITLE
Invalid `hacks library reference` in the documentation

### ISSUE THREAD

**Issue by cospectrum** [pyproject-nix/pyproject.nix#202]
This link is broken: https://pyproject-nix.github.io/build/hacks/default.html

The link is located here: https://pyproject-nix.github.io/pyproject.nix/builders/hacks.html

**Comment by cospectrum** [comment]
I think it's still missing the `pyproject.nix/` prefix

**Comment by adisbladis** [comment]
Jfc I hate github pages. Looks great locally, but they for some really stupid reason they decide to put everything in a subdirectory breaking any link pointing to something relative to the root.
