### ISSUE TITLE
Documentation page returns 404

### ISSUE THREAD

**Issue by mkatychev** [pyproject-nix/pyproject.nix#204]
https://nix-community.github.io/pyproject.nix/ is currently returning a 404, should a CI step be run to restore functionality? current workaround is to clone the repo and `cd doc; mkbook serve`

**Comment by mkatychev** [comment]
It looks like https://pyproject-nix.github.io/pyproject.nix/ is valid after crawling through some uv2nix documentation, this should probably be linked in the repo's about/website section

**Comment by adisbladis** [comment]
The project recently moved into it's own org, and the correct links are in the respective readme's.
Website sections also added.
