### ISSUE TITLE
Override package with cuda version of said package

### ISSUE THREAD

**Issue by arunoruto** [pyproject-nix/pyproject.nix#209]
Because of this project and uv2nix, I switched from poetry to uv to manage the dependencies, so thanks for that!

Now onto my question/issue: I need to install `numba` as a dependency, but somehow I am unable to install the version with cuda, i.e., `numbaWithCuda`. What is the correct way to tell pyproject.nix to take the cuda version?
In my devShells I tried to include it as an extra package, but it colides with the normal numba version:
```nix
            default =
              let
                arg = project.renderers.withPackages {
                  inherit python;
                  extras = [
                    "test"
                    # "docs"
                  ];
                  extraPackages = ps: with ps; [ numbaWithCuda ];
                };

                pythonEnv = python.withPackages arg;
              in
              pkgs.mkShell {
                packages = [
                  pythonEnv
                  self'.packages.yasfpy
                ];
                shellHook = '''';
              };
```

trying to override the default package with cuda didn't work quite either:
```nix
          pyprojectOverrides = final: prev: {
            numba = prev.numbaWithCuda;
            numba = prev.numba.overrideAttrs (old: {
              cudaSupport = true;
            });
          };

          python = pkgs.python3.override {
            packageOverrides = final: prev: {
              inherit (self'.packages)
                refidxdb
                pywigxjpf
                mkdocs-coverage
                ;
              numba = final.pythonPackages.numbaWithCuda;
            };
          };
```

Somehow I am out of ideas of where to inject the correct numba package version type into the project!

**Comment by adisbladis** [comment]
> trying to override the default package with cuda didn't work quite either:

You're mixing concepts here. uv2nix isn't using the nixpkgs python builders but instead the [pyproject.nix builders](https://pyproject-nix.github.io/pyproject.nix/build.html).
What uv2nix generates is completely from pyproject.toml & uv.lock metadata.
When using uv2nix there is no such thing as `cudaSupport`. That's a nixpkgs construct.

If you want to use `numbaWithCuda` using the nixpkgs package set (ignoring `uv.lock` & the uv2nix generated set) this should be correct, [but refer to the  nixpkgs manual](https://nixos.org/manual/nixpkgs/stable/#overriding-python-packages):
``` nix
          python = pkgs.python3.override {
            packageOverrides = final: prev: {
              numba = final.numbaWithCuda;
            };
          };
```
